# Generated by Django 5.0.9 on 2025-03-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikinode',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский'), ('ua', 'Українська'), ('ct', 'Qırımtatarca')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wikiedit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
