# Generated by Django 5.0.9 on 2026-04-09 10:49

import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SovietType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lowest number appears first')),
            ],
            options={
                'verbose_name': 'Soviet Type',
                'verbose_name_plural': 'Soviet Types',
                'ordering': ['translations__name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Soviet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('chat_link', models.URLField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('moderated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_soviets', to=settings.AUTH_USER_MODEL)),
                ('soviet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soviets', to='selfgov.soviettype')),
            ],
            options={
                'verbose_name': 'Soviet',
                'verbose_name_plural': 'Soviets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SovietTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='selfgov.soviettype')),
            ],
            options={
                'verbose_name': 'Soviet Type Translation',
                'db_table': 'selfgov_soviettype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
