# Generated by Django 5.0.9 on 2026-02-27 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovietType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
