# Generated by Django 5.0.9 on 2026-09-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfgov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soviettype',
            options={'ordering': ['order'], 'verbose_name': 'Soviet Type', 'verbose_name_plural': 'Soviet Types'},
        ),
    ]
