# Generated by Django 5.0.9 on 2026-02-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgov', '0002_soviettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soviet',
            name='soviet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selfgov.soviettype'),
        ),
    ]
