# Generated by Django 5.0.9 on 2026-02-28 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgov', '0003_alter_soviet_soviet_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soviet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Soviet', 'verbose_name_plural': 'Soviets'},
        ),
        migrations.AlterModelOptions(
            name='soviettype',
            options={'ordering': ['name'], 'verbose_name': 'Soviet Type', 'verbose_name_plural': 'Soviet Types'},
        ),
        migrations.AddField(
            model_name='soviettype',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lowest number appears first'),
        ),
        migrations.AlterField(
            model_name='soviet',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_soviets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soviet',
            name='soviet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soviets', to='selfgov.soviettype'),
        ),
    ]
