# Generated by Django 5.0.9 on 2025-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('income_option', models.CharField(max_length=255)),
                ('social_status_option', models.CharField(max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('education_option', models.CharField(max_length=255)),
                ('veterans_option', models.CharField(blank=True, max_length=255, null=True)),
                ('dead_veterans_option', models.CharField(blank=True, max_length=255, null=True)),
                ('birthplace', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
                ('participating_option', models.CharField(max_length=255)),
                ('participating_about_question', models.TextField(blank=True, null=True)),
                ('participating_reasons_question', models.TextField(blank=True, null=True)),
                ('participating_more_question', models.TextField(blank=True, null=True)),
                ('politics_interest_level', models.CharField(max_length=255)),
                ('civic_interest_level', models.CharField(max_length=255)),
                ('why_interest_rate_question', models.TextField(blank=True, null=True)),
                ('government_option', models.CharField(max_length=255)),
                ('government_additional_question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
