# Generated by Django 5.0.9 on 2025-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='civic_interest_level',
            new_name='interest_level_2',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='politics_interest_level',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='interest_level_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
