# Generated by Django 5.0.9 on 2025-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialreason',
            name='was_approved',
            field=models.BooleanField(default=False),
        ),
    ]
