# Generated by Django 5.0.9 on 2025-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_socialreason_was_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialreason',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский'), ('ua', 'Українська'), ('ct', 'Qırımtatarca')], max_length=2),
        ),
    ]
