# Generated by Django 5.0.9 on 2026-06-01 10:50

from django.db import migrations, models

def approve_existing_projects(apps, schema_editor):
    project = apps.get_model("project", "Project")
    project.objects.update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_author_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(approve_existing_projects, migrations.RunPython.noop),
    ]
