# Generated by Django 5.0.9 on 2026-09-01 20:14

import ckeditor.fields
import django.db.models.deletion
import edu_event.models
import parler.fields
import parler.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduEventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lowest number appears first')),
            ],
            options={
                'verbose_name': 'Educational Event Type',
                'verbose_name_plural': 'Educational Event Types',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EduEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_edu_events', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='edu_event.edueventtype')),
            ],
            options={
                'verbose_name': 'Educational Event',
                'verbose_name_plural': 'Educational Events',
                'ordering': ['start_date'],
                'permissions': (('can_sign_up', 'Can sign up to Educational Events'),),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EduEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=edu_event.models._generate_code, max_length=8)),
                ('checked_in', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='edu_event.eduevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Educational Event Registration',
                'verbose_name_plural': 'Educational Event Registrations',
            },
        ),
        migrations.CreateModel(
            name='EduEventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('address', models.CharField(max_length=512)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='edu_event.eduevent')),
            ],
            options={
                'verbose_name': 'Educational Event Translation',
                'db_table': 'edu_event_eduevent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EduEventTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='edu_event.edueventtype')),
            ],
            options={
                'verbose_name': 'Educational Event Type Translation',
                'db_table': 'edu_event_edueventtype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='edueventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_user_per_event'),
        ),
        migrations.AddConstraint(
            model_name='edueventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='unique_code_per_event'),
        ),
        migrations.AlterUniqueTogether(
            name='edueventtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='edueventtypetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
